### ISSUE TITLE
No module named 'mti_nma.steps.raw'

### ISSUE THREAD

**Issue by vianamp** [AllenCellModeling/mti_nma#4]
I am getting this after a fresh installation

```Traceback (most recent call last):
  File "/home/matheus.viana/anaconda3/envs/tmp/bin/mti_nma", line 11, in <module>
    load_entry_point('mti-nma', 'console_scripts', 'mti_nma')()
  File "/home/matheus.viana/anaconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/matheus.viana/anaconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/matheus.viana/anaconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/home/matheus.viana/anaconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/aics-normal-modes/tmp/mti_nma/mti_nma/bin/cli.py", line 4, in <module>
    from mti_nma import steps
  File "/allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/aics-normal-modes/tmp/mti_nma/mti_nma/steps/__init__.py", line 3, in <module>
    from .raw import Raw
ModuleNotFoundError: No module named 'mti_nma.steps.raw'```

**Comment by vianamp** [comment]
It seems that we are missing the file `raw/raw.py`. Don't know why tho..

**Comment by vianamp** [comment]
Fixed.
